#define DESPERADO_VINTAGE_PRODUCT "Desperado"
#define DESPERADO_VINTAGE_RELEASE "inspiration"
#define DESPERADO_VINTAGE_VERSION "7.1.0"
#define DESPERADO_VINTAGE_COPYRIGHT "Copyright 2005-2012 Digital Aggregates Corporation, Colorado, USA."
#define DESPERADO_VINTAGE_CONTACT "coverclock@diag.com (Chip Overclock)"
#define DESPERADO_VINTAGE_URL "http://www.diag.com/navigation/downloads/Desperado.html"
#define DESPERADO_VINTAGE_DATE "20120627T155840.507290468-06:00"
#define DESPERADO_VINTAGE_PLATFORM "Linux"
#define DESPERADO_VINTAGE_TARGET "IA32"
#define DESPERADO_VINTAGE_LICENSE "Modified GNU Lesser Public License"
