#define DESPERADO_VINTAGE_PRODUCT "Desperado"
#define DESPERADO_VINTAGE_RELEASE "hawkeye"
#define DESPERADO_VINTAGE_VERSION "6.9.0"
#define DESPERADO_VINTAGE_COPYRIGHT "Copyright 2005-2011 Digital Aggregates Corporation, Colorado, USA."
#define DESPERADO_VINTAGE_CONTACT "coverclock@diag.com (Chip Overclock)"
#define DESPERADO_VINTAGE_URL "http://www.diag.com/navigation/downloads/Desperado.html"
#define DESPERADO_VINTAGE_DATE "20111223T131914.202527371-07:00"
#define DESPERADO_VINTAGE_PLATFORM "Linux"
#define DESPERADO_VINTAGE_TARGET "IA32"
#define DESPERADO_VINTAGE_LICENSE "Modified GNU Lesser Public License"
